### ISSUE TITLE
Error message saying punkt is missing

### ISSUE THREAD

**Issue by finalspy** [louismartin/capfalcnlp#2]
In my environment : 
 - docker container 
 - running miniconda3 
 - with python 3.7
(base on [continuumio/miniconda3](https://hub.docker.com/r/continuumio/miniconda3) docker image - [sources](https://github.com/ContinuumIO/docker-images) )

When I run the example :  `python cli.py --input-file example_text.txt`

I getthe following error : 
```
Traceback (most recent call last):
  File "cli.py", line 14, in <module>
    detections = get_detections(text)
  File "/home/codatalab/capfalcnlp/capfalcnlp/features.py", line 197, in get_detections
    for sentence in get_long_sentences(text):
  File "/home/codatalab/capfalcnlp/capfalcnlp/features.py", line 184, in get_long_sentences
    sentences = split_in_sentences(text)
  File "/home/codatalab/capfalcnlp/capfalcnlp/processing.py", line 74, in split_in_sentences
    return _split_in_sentences_nltk(text, **kwargs)
  File "/home/codatalab/capfalcnlp/capfalcnlp/processing.py", line 69, in _split_in_sentences_nltk
    return get_nltk_sentence_tokenizer(**kwargs).tokenize(text)
  File "/home/codatalab/capfalcnlp/capfalcnlp/processing.py", line 58, in get_nltk_sentence_tokenizer
    return nltk.data.load(f'tokenizers/punkt/{language}.pickle')
  File "/home/codatalab/.local/lib/python3.7/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/home/codatalab/.local/lib/python3.7/site-packages/nltk/data.py", line 875, in _open
    return find(path_, path + [""]).open()
  File "/home/codatalab/.local/lib/python3.7/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/french.pickle

  Searched in:
    - '/home/codatalab/nltk_data'
    - '/opt/conda/envs/capfalcnlp/nltk_data'
    - '/opt/conda/envs/capfalcnlp/share/nltk_data'
    - '/opt/conda/envs/capfalcnlp/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

Adding `nltk.download('punkt')` on [line 50 of processing.py](https://github.com/louismartin/capfalcnlp/blob/24e9f8f8b3d6515be028e948c1588f4ae089600d/capfalcnlp/processing.py#L50) solves the issue.

**Comment by louismartin** [comment]
You may need to double check that it won't be re-downloaded every time you call the method (`nltk.download(...)` should be called only when you install the package).

**Comment by finalspy** [comment]
If launched twice it says "already downloaded" afaik

**Comment by finalspy** [comment]
If launched twice it says : 

```
[nltk_data] Downloading package punkt to <path_to_home>/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
```
